### ISSUE TITLE
Serialization problem using MBrace from REPL when defining abstract types (interfaces).  Okay when compiled.

### ISSUE THREAD

**Issue by evilpepperman** [mbraceproject/MBrace.Azure#132]
When I add an interface/abstract type definition to a program in the REPL (FSI.exe), a previously working script can no longer serialize.  Also, the error is very vague, and it took a while to understand that the mere existence of an interface causes it.  Interestingly, my code worked when compiled, so it may be connected to serializing the FSI environment.

Please allow types which implement interface also work in FSI.

Here are the script and the error:

    #load "ThespianCluster.fsx"
    let cluster = Config.GetCluster() 

    (* uncommenting this will make Vagabond fail to serialize the CLOUD
    open System
    type ICloud =
        inherit IDisposable
        abstract Name : string
    *)

    open MBrace.Core
    let runJob2 () = 
        let reduceAccums = cloud {
            return 1
            }
        reduceAccums |> (cluster).Run
    let v = runJob2 ()

And the error:

    System.ArgumentException: 'this' type cannot be an interface itself.
       at System.RuntimeTypeHandle.VerifyInterfaceIsImplemented(RuntimeTypeHandle handle, RuntimeTypeHandle interfaceHandle)
       at System.RuntimeType.GetInterfaceMap(Type ifaceType)
       at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
       at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapOverrides(MethodBase method, MethodDefinition method_definition)
       at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapMethod(TypeDefinition type_definition, MethodBase method)
       at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapType(Type type, TypeDefinition declaringType)
       at Nessos.Vagabond.AssemblyParser.AssemblyParser.MapType(Type type, TypeDefinition declaringType)
       at Nessos.Vagabond.AssemblyParser.AssemblyParser.Map()
       at Nessos.Vagabond.AssemblyParser.parseDynamicAssemblySlice(AssemblyCompilerState state, Assembly assembly)
       at Nessos.Vagabond.SliceCompiler.compileDynamicAssemblySlice(AssemblyCompilerState state, Assembly dynamicAssembly)
       at Nessos.Vagabond.SliceCompiler.compileAssembly(AssemblyCompilerState state, Assembly assembly)
       at Nessos.Vagabond.SliceCompiler.compileAssemblies@134-1.Invoke(Assembly assembly)
       at Nessos.Vagabond.Utils.MailboxProcessor`1.PostAndReply[Msg,R](FSharpMailboxProcessor`1 m, FSharpFunc`2 msgB)
       at Nessos.Vagabond.VagabondManager.compile(Assembly[] assemblies)
       at Nessos.Vagabond.VagabondManager.ComputeObjectDependencies(Object graph, FSharpOption`1 permitCompilation, FSharpOption`1 includeNativeDependencies)
       at MBrace.Runtime.Components.StoreAssemblyManager.ComputeDependencies[T](T graph) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Components\StoreAssemblyManager.fs:line 294
       at MBrace.Runtime.Components.StoreAssemblyManager.MBrace-Runtime-IAssemblyManager-ComputeDependencies(Object graph) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Components\StoreAssemblyManager.fs:line 308
       at <StartupCode$MBrace-Runtime>.$MBraceClient.CreateProcessAsync@65.Invoke(Unit unitVar) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Runtime\Runtime\MBraceClient.fs:line 66
       at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
       at MBrace.Core.Internals.AsyncExtensions.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\AsyncExtensions.fs:line 101
       at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\dev3\Applications\AMCollateralModelExcemplar\AMCollateral_CloudThespian\BUG-interface.fsx:line 19
    Stopped due to error

**Comment by isaacabraham** [comment]
Interestingly here you are not actually implementing the IDisposable interface - you're just adding that to the list of members that must be implemented by derived classes. I actually didn't even know you could use the "inherits" syntax in this way in F#.

**Comment by eiriktsarpalis** [comment]
This is a bug in Vagabond, good catch!

It's not really a serialization issue, rather it's a failure of the dynamic assembly persisting component to correctly read a piece of IL from reflection. Here's an absolutely minimal reproduction:
```fsharp
#load "ThespianCluster.fsx"
open MBrace.Core

type IFoo = interface end
type IBar = 
    inherit IFoo
    abstract Name : string

let cluster = Config.GetCluster() 
cluster.Run(cloud { return 42})
```
It's interesting to note that removing either of the two lines in the `IBar` implementation will make the error go away. I'll investigate further. In the meantime, you can make the problem go away by moving your type definitions in a class library (which is good practice in general).

**Comment by eiriktsarpalis** [comment]
Fixed in https://github.com/nessos/Vagabond/commit/b66cca893c25b6a3ae4db15b8b28980d55dbd444 & https://github.com/jbevain/mono.reflection/pull/10. I will push an update to MBrace that incorporates the fix soon.

**Comment by eiriktsarpalis** [comment]
The latest MBrace.StartetKit should now fix this problem.
