### ISSUE TITLE
Starter kit problem on Win 10

### ISSUE THREAD

**Issue by gsvgit** [mbraceproject/MBrace.Azure#150]
I use clone of Azure starter kit (commit 755d7492f6cb03442bc085e6caa96934785dbef8). I change AzureCluster.fsx in order to set custom parameters.

On my Win 8 (64 bit) machine examples presented in starter kit work fine, but on Win 10 (details below) with same runtime (.NET, MSVS and other) I get an error on execution of line 33 from 0-provision-azure-cluster.fsx (```let deployment = Config.ProvisionCluster()```) Error message provided below. 

OS Name	Microsoft Windows 10 Pro
Version	10.0.10586 Build 10586
System Type	x64-based PC

```
System.Security.Cryptography.CryptographicException: The profile for the user is a temporary profile.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.X509Certificates.X509Utils._LoadCertFromBlob(Byte[] rawData, IntPtr password, UInt32 dwFlags, Boolean persistKeySet, SafeCertContextHandle& pCertCtx)
   at System.Security.Cryptography.X509Certificates.X509Certificate.LoadCertificateFromBlob(Byte[] rawData, Object password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
   at MBrace.Azure.Management.Common.SubscriptionClient.Activate(Subscription subscription)
   at MBrace.Azure.Management.SubscriptionManager.Create(Subscription subscription, Region defaultRegion, FSharpOption`1 logger, FSharpOption`1 logLevel)
   at MBrace.Azure.Management.SubscriptionManager.FromPublishSettings(PublishSettings publishSettings, Region defaultRegion, FSharpOption`1 subscriptionId, FSharpOption`1 logger, FSharpOption`1 logLevel)
   at MBrace.Azure.Management.SubscriptionManager.FromPublishSettingsFile(String publishSettingsFile, Region defaultRegion, FSharpOption`1 subscriptionId, FSharpOption`1 logger, FSharpOption`1 logLevel)
   at FSI_0002.Config.ProvisionCluster() in C:\gsv\projects\YC\mbrace_1.2.2\MBrace.StarterKit\HandsOnTutorial\AzureCluster.fsx:line 64
   at <StartupCode$FSI_0004>.$FSI_0004.main@() in C:\gsv\projects\YC\mbrace_1.2.2\MBrace.StarterKit\HandsOnTutorial\0-provision-azure-cluster.fsx:line 33
Stopped due to error
```

**Comment by eiriktsarpalis** [comment]
I'm using the same Windows 10 build but not experiencing the issue. A quick google search of your stacktrace reveals that there might be an issue with your windows account permissions.

**Comment by isaacabraham** [comment]
@gsvgit can this be closed?

**Comment by gsvgit** [comment]
Yes, thanks.
