### ISSUE TITLE
Issue with Cloud.Parallel when trying to read contents of CloudFiles

### ISSUE THREAD

**Issue by lenadroid** [mbraceproject/MBrace.Azure#16]
I have the code:
```
let! files = CloudFile.Enumerate dirName
let! text = files |> Array.map (CloudFile.ReadAllText) |> Cloud.Parallel
```

When I try to run it, there is an exception:
```
26022015 09:38:47.869 +02:00 : Created process 74db95339f1849579478e6fa9dbbcd29
System.IO.FileNotFoundException: processe360d49\blobcell:304767d8c72c495bb974ad2e90f842e3
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at <StartupCode$MBrace-Runtime-Core>.$FileStoreCache.attemptRead@150-2.Invoke(Tuple`2 _arg2) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 168
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at Cloud.Parallel[T](seq<Cloud<T>> computations)
--- End of stack trace from previous location where exception was thrown ---
   в Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   в <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@116-1.Invoke(Result`1 _arg2) в C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:строка 116
   в Microsoft.FSharp.Control.AsyncBuilderImpl.args@797-1.Invoke(a a)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 134
   at MBrace.Azure.Client.Process`1.AwaitResult() in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 110
   at <StartupCode$MBrace-Azure-Client>.$Client.RunAsync@103-2.Invoke(Unit unitVar) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 103
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@813.Invoke(AsyncParams`1 args)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 134
   at MBrace.Azure.Client.Runtime.Run[T](Cloud`1 workflow, FSharpOption`1 cancellationToken, FSharpOption`1 faultPolicy) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 125
   at <StartupCode$FSI_0008>.$FSI_0008.main@() in D:\Programming\github\mbrace-on-brisk-starter\src\Demos\script.fsx:line 180
Stopped due to error
> 
```
I think it's something related to Cloud.Parallel, because when I do "Array.get files 0" and read the contents - it works fine

I am using brisk.
dirName in my snippet is "processe360d49"

**Comment by krontogiannis** [comment]
Thanks, I'll look into this.

**Comment by krontogiannis** [comment]
Closing this for now. User and Runtime data are in separate folders since #22.

**Comment by krontogiannis** [comment]
Closing this for now. User and Runtime data are in separate folders since #22.
