### ISSUE TITLE
Transient error on simplest of workflows

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#17]
I ran this at the start of a new MBrace F# Interactive session
```
// Create a cloud workflow, don't execute it
let workflow = cloud { return "Hello world!" }

// Actually execute the workflow and get a handle to the overall job
let job = workflow |> cluster.CreateProcess
```
and I got this the first time - after that it worked ok:
```
System.Exception: internal error: dependency graph is not a DAG.
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at MBrace.Azure.Client.Runtime.CreateProcess[T](Cloud`1 workflow, FSharpOption`1 name, FSharpOption`1 defaultDirectory, FSharpOption`1 fileStore, FSharpOption`1 defaultAtomContainer, FSharpOption`1 atomProvider, FSharpOption`1 defaultChannelContainer, FSharpOption`1 channelProvider, FSharpOption`1 cancellationToken, FSharpOption`1 faultPolicy) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 49
   at <StartupCode$FSI_0029>.$FSI_0029.main@() in C:\GitHub\dsyme\mbrace-on-brisk-starter\src\Demos\1-hello-world.fsx:line 33
```

Strange.

**Comment by eiriktsarpalis** [comment]
This looks like a Vagabond bug. We fixed an issue like this about a month ago, we'll have to roll out the nuget packages to brisk to find out if it persists.

**Comment by isaacabraham** [comment]
I'm upgrading Brisk today to 0.6.0 alpha of MBrace on Azure.

**Comment by dsyme** [comment]
Closing assuming it is fixed, will reopen if I see it again
