### ISSUE TITLE
Cannot GetProcesses()

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#18]
On a new cluster, with a cleansed service bus and storage account, whilst I can get a handle to a cluster, calling GetProcesses() returns:

      System.AggregateException: One or more errors occurred. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
         at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex)
         at Microsoft.WindowsAzure.Storage.Blob.CloudBlobSharedImpl.<>c__DisplayClassa.<FetchAttributesImpl>b__9(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)
         at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
         --- End of inner exception stack trace ---
         at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
         at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndOpenRead(IAsyncResult asyncResult)
         at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
         --- End of inner exception stack trace ---

         at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 134
         at MBrace.Azure.Client.Runtime.GetProcesses() in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 152
         at <StartupCode$FSI_0005>.$FSI_0005.main@()
      ---> (Inner Exception #0) Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
         at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex)
         at Microsoft.WindowsAzure.Storage.Blob.CloudBlobSharedImpl.<>c__DisplayClassa.<FetchAttributesImpl>b__9(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)
         at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
         --- End of inner exception stack trace ---
         at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
         at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndOpenRead(IAsyncResult asyncResult)
         at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
      Request Information
      RequestID:8cd7fd41-0001-001a-72f6-9d87cb000000
      RequestDate:Fri, 27 Feb 2015 23:04:01 GMT
      StatusMessage:The specified blob does not exist.
      <---

      Stopped due to error

This is on the version of code used on Brisk - so slightly out of date. Any idea why I might be getting this?

**Comment by krontogiannis** [comment]
Hm, did you clean the storage account manually or using some client API?

**Comment by isaacabraham** [comment]
Just went through and deleted all containers and tables that had "process" or "mbrace" in them.

**Comment by krontogiannis** [comment]
Hm, seems to me that the process records still exist in table storage but the blob they are referencing are deleted. Is `.ShowProcesses` also failing?

**Comment by isaacabraham** [comment]
no, that works.

**Comment by isaacabraham** [comment]
where does ShowProcesses get its data from?

**Comment by krontogiannis** [comment]
Ok, I see. ShowProcesses and GetProcesses get the info from the same table. The difference is that GetProcesses doen't just print info, instead returns Process<'T> objects. These objects need to hold more info like process dependencies, result, cancellation tokens, e.t.c things that are stored in blobs.

**Comment by isaacabraham** [comment]
is there anywhere documented what tables / blobs / queues / topics are used (and what for)?

**Comment by krontogiannis** [comment]
No, not at the moment. But I'm working on a [refactoring](https://github.com/krontogiannis/MBrace.Azure/tree/refactoring/runtime-folders) on the Configuration object and where runtime state is saved, so that you can ran multiple runtimes in the same storage/service bus accounts, do not create different containers/table per process, etc.

With the pull request I'm planning on uploading a document describing exactly what is stored in each container etc :)

**Comment by isaacabraham** [comment]
awesome :-) I was going to say - I noticed one table per process - for same reason as containers this should probably be a single table per cluster IMHO partitioned e.g. on process - in Azure terms this shards / scales out in basically the same way :-)
