### ISSUE TITLE
Cannot resolve dependency to assembly 'MBrace.Core, Version=0.9.2.0, Culture=neutral, PublicKeyToken=null' because it has not been preloaded

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#23]
The code further below gives the following error on Elastacloud (this is probably an MBrace.Core issue, perhaps a known one).  

Here's the exception
```
System.IO.FileLoadException: Cannot resolve dependency to assembly 'MBrace.Core, Version=0.9.2.0, Culture=neutral, PublicKeyToken=null' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Nessos.Vagabond.AssemblyParser.tryRemapReferencedType(DynamicAssemblyCompilerState state, Type t) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyParser.fs:line 100
   at Nessos.Vagabond.Utils.memoize@75.Invoke(a x) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 79
   at Nessos.Vagabond.AssemblyParser.parseConfiguration@129.Nessos-Vagabond-Cecil-IAssemblyParserConfig-RemapReference(Type type, Type& outType) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyParser.fs:line 154
   at Nessos.Vagabond.Cecil.AssemblyParser.MapReference(Type t, TypeReference type) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond.Cecil\AssemblyParser.cs:line 736
   at Nessos.Vagabond.Cecil.AssemblyParser.MapReference(Type t, TypeReference type) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond.Cecil\AssemblyParser.cs:line 733
   at Nessos.Vagabond.Cecil.AssemblyParser.CreateReference(MethodBase method, MethodReference context) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond.Cecil\AssemblyParser.cs:line 693
   at Nessos.Vagabond.Cecil.AssemblyParser.MapInstructions(MethodBase method, MethodDefinition method_definition) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond.Cecil\AssemblyParser.cs:line 369
   at Nessos.Vagabond.Cecil.AssemblyParser.MapMethodBody(MethodBase method, MethodDefinition method_definition) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond.Cecil\AssemblyParser.cs:line 350
   at Nessos.Vagabond.Cecil.AssemblyParser.MapType(Type type, TypeDefinition declaringType) in 
```

When I do this:

```
System.AppDomain.CurrentDomain.GetAssemblies() |> Seq.find (fun n -> n.FullName.Contains("MBrace.Core"))
```
the MBrace.Core is loaded (though perhaps not for reflection-only)

Here's the code
```

#load "credentials.fsx"
#load "lib/collections.fsx"

open MBrace
open MBrace.Azure
open MBrace.Azure.Client
open MBrace.Azure.Runtime
open MBrace.Streams
open MBrace.Workflows
open Nessos.Streams

// First connect to the cluster
let cluster = Runtime.GetHandle(config)

/// Cloud actor instance
type CloudActor<'T> private (sender: ISendPort<'T>, task: ICloudTask<unit>, cts: ICloudCancellationTokenSource) =
    /// Deploys a new actor instance with provided behaviour on cluster
    static member Create(behaviour) =  cloud {
        let! cts = Cloud.CreateCancellationTokenSource()
        let! sp, rp = CloudChannel.New<'T> ()
        let! task = Cloud.StartAsCloudTask(behaviour rp, faultPolicy = FaultPolicy.NoRetry, cancellationToken = cts.Token)
        return CloudActor<'T>(sp, task, cts)
    }
    /// Post message to actor
    member a.Post(msg : 'T) = cloud {
        return! sender.Send msg
    }

    /// Post message to actor, awaiting for reply
    member a.PostWithReply(messageBuilder : ISendPort<'R> -> 'T) = cloud {
        let! sp,rp = CloudChannel.New<'R> ()
        use rp = rp
        do! a.Post(messageBuilder sp)
        return! rp.Receive()
    }

    /// Kills the actor instance
    member a.Kill () = cts.Cancel()

    interface ICloudDisposable with
        member a.Dispose () = cloud { cts.Cancel() }


// sample implementation : counter

type Counter =
    | IncrementBy of int
    | GetValue of ISendPort<int>
    | Reset of int

let rec behaviour (state : int) (mbox : IReceivePort<Counter>) = cloud {
    let! msg = mbox.Receive()
    match msg with
    | IncrementBy i -> return! behaviour (state + i) mbox
    | Reset c -> return! behaviour c mbox
    | GetValue rc -> 
        do! rc.Send state
        return! behaviour state mbox
}

// deploy actor to cluster
let actor = CloudActor.Create (behaviour 0) |> cluster.Run

cloud {
    for i in [1 .. 100] do 
      do! actor.Post (IncrementBy i)
}
|> cluster.Run
```

**Comment by eiriktsarpalis** [comment]
I can't reproduce this error, but I'm still getting a `NullReferenceException` that seems Vagabond-related.

**Comment by dsyme** [comment]
I'll close this since it was no repro, let's reopen if we see it again
