### ISSUE TITLE
Cache should be initialized once.

### ISSUE THREAD

**Issue by krontogiannis** [mbraceproject/MBrace.Azure#3]
Running Runtime.GetHandle(config) twice throws this exception:

    System.InvalidOperationException: A a cache store has already been declared under 'DefaultCacheContext'.
    at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
    at MBrace.Runtime.Store.FileStoreCache.RegisterLocalCacheStore(ICloudFileStore localCacheStore, FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 116
    at MBrace.Runtime.Store.FileStoreCache.RegisterLocalFileSystemCache(FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 126
    at MBrace.Azure.Client.StoreClient..ctor(Configuration config) in C:\workspace\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 200
    at MBrace.Azure.Client.StoreClient.Create(Configuration config) in C:\workspace\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 237
    at MBrace.Azure.Client.Runtime..ctor(Configuration config) in C:\workspace\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 27
    at MBrace.Azure.Client.Runtime.GetHandle(Configuration config, FSharpOption`1 waitWorkerCount) in C:\workspace\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 175
    at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\workspace\MBrace.Azure\tests\MBrace.Azure.Runtime.Tests\test.fsx:line 42

**Comment by lenadroid** [comment]
Strange, I am getting the same when I try to run the examples in mbrace.fsx from here: https://github.com/elastacloud/mbrace-on-brisk-starter/blob/master/src/Demos/mbrace.fsx

```
System.InvalidOperationException: A a cache store has already been declared under 'DefaultCacheContext'.
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at MBrace.Runtime.Store.FileStoreCache.RegisterLocalCacheStore(ICloudFileStore localCacheStore, FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 116
   at MBrace.Runtime.Store.FileStoreCache.RegisterLocalFileSystemCache(FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 126
   at MBrace.Azure.Client.StoreClient..ctor(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 200
   at MBrace.Azure.Client.StoreClient.Create(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 237
   at MBrace.Azure.Client.Runtime..ctor(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 27
   at MBrace.Azure.Client.Runtime.GetHandle(Configuration config, FSharpOption`1 waitWorkerCount) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 175
   at <StartupCode$FSI_0011>.$FSI_0011.main@() in D:\Programming\github\mbrace-on-brisk-starter\src\Demos\mbrace.fsx:line 25
Stopped due to error
```

**Comment by krontogiannis** [comment]
Hey, the MBrace.Azure assemblies that Brisk is using are quite outdated. Next week we will be releasing a nuget package for this runtime so the whole experience will be a lot smoother. Most of the issues you are having are already fixed in our branches.
