### ISSUE TITLE
Please make process deserialization errors fault the process

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#38]
I got the error below. It would be really great if faults like this actually faulted the process, rather than leaving it in "Posted" or "Running" state.  

This was using 0.6.1-alpha and I think the root cause is likely to be the issue fixed by #28 - the DLL is non-dynamic and had already been loaded into the AppDomain.

Even killing the process doesn't get rid of it :)

      4f53596f73c34827bc7413a842d7a939  Kill requested  False      00:21:24.1787059    0 /   0 /   0 /   1  string                         11/03/2015 21:51:58 +00:00  N/A                        
      98dbd86a42504d85a0a1ba1b935388ba  Kill requested  False      00:07:44.4276714    0 /   0 /   0 /   1  FSharpWeb2.Controllers.Car []  11/03/2015 22:05:38 +00:00  N/A                        

```
Nessos.FsPickler.FsPicklerException: Error deserializing object of type 'MBrace.Azure.Runtime.Job'. ---> System.TypeLoadException: Could not load type '<StartupCode$FSharpWeb1>.$Global.asax+Get@41' from assembly 'FSharpWeb1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at Nessos.FsPickler.ReflectionCache.loadMemberInfo(FSharpOption`1 tyConv, FSharpFunc`2 loadAssembly, FSharpFunc`2 getMethodSignature, CompositeMemberInfo mI) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\ReflectionCache.fs:line 175
   at Nessos.FsPickler.Utils.BiMemoizer`2.G(S s) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Utils\Utils.fs:line 135
   at Nessos.FsPickler.ReflectionPicklers.memberInfoReader@161.Invoke(ReadState r, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\ReflectionPicklers.fs:line 253
   at <StartupCode$FsPickler>.$CompositePickler.reader@112.Invoke(ReadState r, String t) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 112
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 255
   at classDeserializer(Pickler[] , ReadState )
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at Nessos.FsPickler.Pickler`1.UntypedRead(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\Pickler.fs:line 59
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 242
   at classDeserializer(Pickler[] , ReadState )
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at Nessos.FsPickler.Pickler`1.UntypedRead(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\Pickler.fs:line 59
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 242
   at classDeserializer(Pickler[] , ReadState )
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at Nessos.FsPickler.Pickler`1.UntypedRead(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\Pickler.fs:line 59
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 242
   at recordDeserializer(Pickler[] , ReadState )
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at Nessos.FsPickler.RootSerialization.readRootObject[T](IPicklerResolver resolver, ReflectionCache reflectionCache, IPickleFormatReader formatter, FSharpOption`1 streamingContext, Pickler`1 pickler) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\RootSerialization.fs:line 49
   --- End of inner exception stack trace ---
   at Nessos.FsPickler.RootSerialization.readRootObject[T](IPicklerResolver resolver, ReflectionCache reflectionCache, IPickleFormatReader formatter, FSharpOption`1 streamingContext, Pickler`1 pickler) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\RootSerialization.fs:line 54
   at Nessos.FsPickler.FsPicklerSerializer.Deserialize[T](Stream stream, FSharpOption`1 streamingContext, FSharpOption`1 encoding, FSharpOption`1 leaveOpen) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\Serializer.fs:line 98
   at <StartupCode$FsPickler>.$Serializer.f@156-7[T](FsPicklerSerializer bp, FSharpOption`1 streamingContext, FSharpOption`1 encoding, Stream m) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\Serializer.fs:line 245
   at Nessos.FsPickler.FsPicklerSerializer.UnPickle[T](Byte[] pickle, FSharpOption`1 streamingContext, FSharpOption`1 encoding) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\Serializer.fs:line 245
   at <StartupCode$MBrace-Azure-Runtime>.$Worker.workerLoop@130-9.Invoke(Unit _arg15) in c:\Users\eirik\Development\nessos\MBrace.Azure\src\MBrace.Azure.Runtime\Worker.fs:line 131
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a) 
```

**Comment by krontogiannis** [comment]
Yeah, I've been working on this kind of stuff. This kind of errors will return `FaultException` and complete either the whole process or current job.

The issue with the non-dynamic assembly should by fixed by AppDomains.
