### ISSUE TITLE
Resetting a cluster sometimes fails

### ISSUE THREAD

**Issue by isaacabraham** [mbraceproject/MBrace.Azure#43]
When resetting a cluster, it (I assume) drops and recreates the Tables etc.. with 409 conflicts. I think that this is because the Azure SDK (when dropping tables) returns success when it won't allow you to create a new Table because Azure is still really deleting them in the background.

Here's an error trace: -

    Id  Hostname  % CPU / Cores  % Memory / Total(MB)  Network(ul/dl : kbps)  Jobs  Process Id  Initialization Time  Heartbeat  Is active
    --  --------  -------------  --------------------  ---------------------  ----  ----------  -------------------  ---------  ---------
    val it : unit = ()
    Failed to log System.AggregateException: One or more errors occurred. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (409) Conflict. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
      at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result, TableOperation operation, HttpWebResponse resp, Exception ex)
      at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
      --- End of inner exception stack trace ---
      at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
      at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult asyncResult)
      at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
      --- End of inner exception stack trace ---
    ---> (Inner Exception #0) Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (409) Conflict. ---> System.Net.WebException: The remote server returned an error: (409) Conflict.
      at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPreProcess(TableResult result, TableOperation operation, HttpWebResponse resp, Exception ex)
      at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
      --- End of inner exception stack trace ---
      at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
      at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult asyncResult)
      at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
    Request Information
    RequestID:941b438e-0002-0028-7f6f-942f77000000
    RequestDate:Mon, 16 Mar 2015 18:53:55 GMT
    StatusMessage:Conflict
    ErrorCode:TableBeingDeleted

**Comment by isaacabraham** [comment]
Have you confirmed that the change to Task works? In my experience using the Azure SDK it actually returns once the delete has happened but /before/ the table name is available to be recreated again.

**Comment by krontogiannis** [comment]
Yeah! `Reset` is going to recreate the tables and keep retrying until they are created.
Accidentally in a refactoring AwaitTask was replaced with AwaitIAsyncResult, so no exception was thrown and `Reset` did no retries.

Compare this
```fsharp

Async.AwaitIAsyncResult(Task.Factory.StartNew(fun () -> Thread.Sleep(2000) ; raise(exn())))
|> Async.RunSynchronously
```
and this
```fsharp
Async.AwaitTask<unit>(Task.Factory.StartNew(fun () -> Thread.Sleep(2000) ; raise(exn())))
|> Async.RunSynchronously
```

The first one will return true, but the second one will raise an exc.

**Comment by isaacabraham** [comment]
Ahhhh missed that. Yes, that should work :-) Cool.
