### ISSUE TITLE
Vagabond file access gives System.IO.IOException: The process cannot access the file

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#54]
This is using 0.6.4 (the latest on Brisk).

I think Vagabond has been restructured but I'm not sure if that was before or after 0.6.4.  (Having a cluster.ShowInfo() call which lists software version to report in a bug trace etc. would be useful.)

```
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The process cannot access the file 'C:\Resources\directory\df2e2f7639914a139eff2227a7b72050.MBraceWorkerRole.CustomTempLocalStore\mbrace-process-4032\vagabond\libiomp5md.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at FSI_0071.UseNative()
   at FSI_0161.f@1-3(Int32 i)
   at FSI_0161.nativeMathJob@133-35.Invoke(Int32 value)
   at Nessos.Streams.ParStream.createTask@74-2.Invoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Nessos.Streams.ParStream.ofArray@63.Nessos-Streams-ParStream`1-Apply[R](Collector`2 )
   at MBrace.Streams.CloudStreamModule.createTask@89-2.Invoke(Collector`2 _arg3)
   at MBrace.Builders.Bind@319-7.Invoke(ExecutionContext ctx, T t) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\Builders.fs:line 319
   at Cloud.Parallel(seq<Cloud<Double>> computations)
--- End of stack trace from previous location where exception was thrown ---
   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@135-2.Invoke(Unit _arg4) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 135
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
>    at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 136
   at <StartupCode$FSI_0248>.$FSI_0248.main@()
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'C:\Resources\directory\df2e2f7639914a139eff2227a7b72050.MBraceWorkerRole.CustomTempLocalStore\mbrace-process-4032\vagabond\libiomp5md.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at FSI_0071.UseNative()
   at FSI_0161.f@1-3(Int32 i)
   at FSI_0161.nativeMathJob@133-35.Invoke(Int32 value)
   at Nessos.Streams.ParStream.createTask@74-2.Invoke()
   at System.Threading.Tasks.Task.Execute()<---
```

**Comment by eiriktsarpalis** [comment]
This looks like a user-level race on `UseNative`. It seems that two collocated mbrace jobs are attempting to write on the same path. Synchronizing with a mutex would probably fix this. The reason why the `.dll` appears to be inside the vagabond cache directory is because of this [line](https://github.com/elastacloud/mbrace-on-brisk-starter/blob/master/src/Demos/6-nuget-packages.fsx#L107).

**Comment by dsyme** [comment]
I see, yes, that's it, thanks
