### ISSUE TITLE
Running GetHandle twice ni the same session

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#6]
I'm using the Elastacloud preview.

At the moment it's not possible to run 

    let cluster = Runtime.GetHandle(config)

twice in a single F# Interactive session - it complains with the error below. Can this be fixed?

```
System.InvalidOperationException: A a cache store has already been declared under 'DefaultCacheContext'.
   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at MBrace.Runtime.Store.FileStoreCache.RegisterLocalCacheStore(ICloudFileStore localCacheStore, FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 116
   at MBrace.Runtime.Store.FileStoreCache.RegisterLocalFileSystemCache(FSharpOption`1 cacheContext, FSharpOption`1 cacheBehavior) in C:\dev\github-repositories\MBrace.Core\src\MBrace.Runtime.Core\Store\FileStoreCache.fs:line 126
   at MBrace.Azure.Client.StoreClient..ctor(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 200
   at MBrace.Azure.Client.StoreClient.Create(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\StoreClient.fs:line 237
   at MBrace.Azure.Client.Runtime..ctor(Configuration config) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 27
   at MBrace.Azure.Client.Runtime.GetHandle(Configuration config, FSharpOption`1 waitWorkerCount) in C:\Users\developer001\Source\Repos\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 175
   at <StartupCode$FSI_0009>.$FSI_0009.main@() in C:\GitHub\dsyme\mbrace-on-brisk-starter\src\Demos\7-cloud-files.fsx:line 24


```

**Comment by krontogiannis** [comment]
Yeah that's a [known](https://github.com/mbraceproject/MBrace.Azure/issues/3) issue and it's [fixed](https://github.com/mbraceproject/MBrace.Azure/commit/d5f3ea9d71ce4bc38f2717a7423f9b57da30ee0c).

Unfortunately, I don't think that there is a way to work around this without reseting the interactive session.

**Comment by dsyme** [comment]
Great to know!!

I don't mind about it at the moment, it's fabulous to know that progress is being made. I'll just keep recording this kind of issue from the Elastacloud preview as a sort of feedback mechanism.
