### ISSUE TITLE
Multi-threaded job submission 

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Azure#60]
When using the MBrace client in the F# REPL, we were submitting multiple jobs simultaneously using ```arr |> Array.Parallel.map (fun data -> ... cluster.CreateProcess (cloud { ... data ...  })```

We got the following call stack. We think it is because vagabond is using a crypto primitive which is not thread safe.

```
System.Security.Cryptography.CryptographicException: Hash not valid for use in specified state.

   at System.Security.Cryptography.CryptographicException.ThrowCryptographicException(Int32 hr)
   at System.Security.Cryptography.Utils.HashData(SafeHashHandle hHash, Byte[] data, Int32 cbData, Int32 ibStart, Int32 cbSize)
   at System.Security.Cryptography.MD5CryptoServiceProvider.HashCore(Byte[] rgb, Int32 ibStart, Int32 cbSize)
   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Stream inputStream)
   at Nessos.Vagabond.AssemblyNaming.AssemblyIdGenerator.computeHash(String path) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyNaming.fs:line 35
   at Nessos.Vagabond.AssemblyNaming.AssemblyIdGenerator.getManagedAssemblyId(Assembly assembly) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\AssemblyNaming.fs:line 49
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Nessos.Vagabond.DependencyAnalysis.traverseDependencyGraph@91(FSharpFunc`2 ignoreF, Boolean requireLoaded, FSharpOption`1 state, FSharpMap`2 graph, FSharpList`1 remaining) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 94
   at Nessos.Vagabond.DependencyAnalysis.traverseDependencyGraph@91-1.Invoke(FSharpMap`2 graph, FSharpList`1 remaining) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 91
   at Nessos.Vagabond.DependencyAnalysis.traverseDependencies(FSharpFunc`2 ignoreF, Boolean requireLoaded, FSharpOption`1 state, IEnumerable`1 assemblies) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 99
   at MBrace.Azure.Runtime.Primitives.BlobAssemblyManager.ComputeDependencies[T](T graph) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Runtime\Primitives\BlobAssemblyManager.fs:line 191
   at <StartupCode$MBrace-Azure-Client>.$Client.CreateProcessAsync@196.Invoke(Unit unitVar) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 198
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at <StartupCode$FSI_0010>.$FSI_0010.main@() in C:\dev\vstfmsrc\cid\Users\a-inmun\FetchEditorImageUploader\ImageDuplicateFinder\script.fsx:line 116

```

**Comment by eiriktsarpalis** [comment]
I can reproduce this consistently. It has been fixed in https://github.com/nessos/Vagabond/commit/9ba32b5ce678fa4826ec22b944409f4d5ddaca15

**Comment by dsyme** [comment]
Wow, that was fast!  So it sounds like the expectation is that multi-threaded job submission will work.

**Comment by eiriktsarpalis** [comment]
Correct, it should work.
