### ISSUE TITLE
Error from long running (or large-serialization) process 

### ISSUE THREAD

**Issue by kip9000** [mbraceproject/MBrace.Azure#63]
We saw this stack trace from a job that ran for a long time and then faulted.  We're not sure if it is a bug (we are re-running it) but thought the stack trace may be helpful:

```
MBrace.FaultException: Failed to download PickledJob. ---> Nessos.FsPickler.FsPicklerException: Error deserializing object of type 'MBrace.Azure.Runtime.PickledJob'. ---> Microsoft.WindowsAzure.Storage.StorageException: The client could not finish the operation within specified timeout. ---> System.TimeoutException: The client could not finish the operation within specified timeout.
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.DownloadRangeToStream(Stream target, Nullable`1 offset, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.BlobReadStream.DispatchReadSync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BinaryReader.ReadBytes(Int32 count)
   at classDeserializer(Pickler[] , ReadState )
   at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at recordDeserializer(Pickler[] , ReadState )
>    at Nessos.FsPickler.CompositePickler`1.Read(ReadState state, String tag) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\Pickler\CompositePickler.fs:line 265
   at Nessos.FsPickler.RootSerialization.readRootObject[T](IPicklerResolver resolver, ReflectionCache reflectionCache, IPickleFormatReader formatter, FSharpOption`1 streamingContext, Pickler`1 pickler) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\RootSerialization.fs:line 49
   --- End of inner exception stack trace ---
   at Nessos.FsPickler.RootSerialization.readRootObject[T](IPicklerResolver resolver, ReflectionCache reflectionCache, IPickleFormatReader formatter, FSharpOption`1 streamingContext, Pickler`1 pickler) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\RootSerialization.fs:line 54
   at Nessos.FsPickler.FsPicklerSerializer.Deserialize[T](Stream stream, FSharpOption`1 streamingContext, FSharpOption`1 encoding, FSharpOption`1 leaveOpen) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\Serializer.fs:line 98
   at <StartupCode$MBrace-Azure-Runtime>.$Queues.GetPayloadAsync@72-2.Invoke(Stream _arg2) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Runtime\Primitives\Queues.fs:line 74
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---

   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@135-2.Invoke(Unit _arg4) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 135
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 136
   at FSI_0080.it@188-19.Invoke(Process`1 j) in C:\dev\vstfmsrc\cid\Users\a-inmun\FetchEditorImageUploader\ImageDuplicateFinder\script.fsx:line 188
   at Microsoft.FSharp.Collections.ArrayModule.Choose[T,TResult](FSharpFunc`2 chooser, T[] array)
   at <StartupCode$FSI_0080>.$FSI_0080.main@()
Stopped due to error
```

**Comment by krontogiannis** [comment]
Hmm, a wild guess is that you are using a `Cloud.Parallel` or multiple `CreateProcess` that capture a big object and during the job deserialization blob storage [timeouts](https://msdn.microsoft.com/en-us/library/azure/dd179431.aspx) are exceeded. Is that the case?

Can we get a code sample for this, or some overview of the code?

**Comment by dsyme** [comment]
It was just one job out of 280 - for the puppy image processing task.  Nothing remarkable - just 280 calls to CreateProcess done in serial where each captured and returned a chunk of data.  We identified and re-ran the specific job (which is running now) - it was the largest of the jobs.

Feel free to close this for now - or add it to an FAQ in the docs.  The error message was reasonable given what happened.

**Comment by krontogiannis** [comment]
In cases of capturing big chunks of data using a pattern like [this](https://github.com/mbraceproject/MBrace.Core/issues/55#issuecomment-89076303) (using `CloudCell`) can actually be very helpful.
