### ISSUE TITLE
Anotjher stack trace from a long-running job

### ISSUE THREAD

**Issue by kip9000** [mbraceproject/MBrace.Azure#64]
Here's another stack trace from a long-running job.  The worker may have run out of memory, we're not sure.  Close this issue once you've digested it since this stack trace doesn't look actionable :)

```
      MBrace.FaultException: Fault exception when running job '5199ba300c684abfb2ca8421a2e55ee4', faultCount '1'

   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@135-2.Invoke(Unit _arg4) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 135
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 136
   at FSI_0097.results@189-5.Invoke(Process`1 j) in C:\dev\vstfmsrc\cid\Users\a-inmun\FetchEditorImageUploader\ImageDuplicateFinder\script.fsx:line 190
        {Data = dict [];
         HResult = -2146233088;
         HelpLink = null;
         InnerException = null;
         Message = "Fault exception when running job '5199ba300c684abfb2ca8421a2e55ee4', faultCount '1'";
         Source = "MBrace.Core";
         StackTrace = "
   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@135-2.Invoke(Unit _arg4) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 135
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 136
   at FSI_0097.results@189-5.Invoke(Process`1 j) in C:\dev\vstfmsrc\cid\Users\a-inmun\FetchEditorImageUploader\ImageDuplicateFinder\script.fsx:line 190";
         TargetSite = T RunSync[T](Microsoft.FSharp.Control.FSharpAsync`1[T], Microsoft.FSharp.Core.FSharpOption`1[System.Threading.CancellationToken]);};
```

**Comment by krontogiannis** [comment]
This is the expected behaviour. You can try using a custom `FaultPolicy` in `CreateProcess` (default is `NoRetry`), but if job is running the worker out of memory there isn't much you can do :)

**Comment by dsyme** [comment]
Thanks. (We're not totally sure if it ran out of memory - but perhaps that possible cause could be mentioned in the diagnostic )
