### ISSUE TITLE
Weird behaviour with non-serializable type 

### ISSUE THREAD

**Issue by palladin** [mbraceproject/MBrace.Azure#66]
The following code never completes
```fsharp
cloud {
    let client = new System.Net.WebClient()
    return client
} |> runtime.Run
```
and the ShowProcessInfo 
```
 ecf3902f07b54378af178781629aae64    Running  False      00:02:00.5131108   -9 /  10 /   0 /   1  System.Net.WebClient []  20/4/2015 3:07:34 μμ +00:00  
```

**Comment by krontogiannis** [comment]
Now a proper exception is returned
```
MBrace.Core.FaultException: Failed to execute job '1fa014020b4d448e8f0940ea99c49ff3' ---> Nessos.FsPickler.NonSerializableTypeException: Type 'MBrace.Azure.Runtime.Primitives.Result`1[System.Net.WebClient]' contains non-serializable field of type 'System.Net.WebClient'.
   at Nessos.FsPickler.PicklerCache.Nessos-FsPickler-IPicklerResolver-Resolve[T]() in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\PicklerGeneration\PicklerCache.fs:line 54
   at Nessos.FsPickler.FsPicklerSerializer.Serialize[T](Stream stream, T value, FSharpOption`1 streamingContext, FSharpOption`1 encoding, FSharpOption`1 leaveOpen) in c:\Users\eirik\Development\nessos\FsPickler\src\FsPickler\FsPickler\Serializer.fs:line 45
   at <StartupCode$MBrace-Azure-Runtime>.$Cells.Create@70-6.Invoke(CloudBlobStream _arg10) in C:\workspace\krontogiannis\MBrace.Azure\src\MBrace.Azure.Runtime\Primitives\Cells.fs:line 71
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@803.Invoke(AsyncParams`1 args)
   --- End of inner exception stack trace ---

   at Microsoft.FSharp.Core.Operators.Raise[T](Exception exn)
   at <StartupCode$MBrace-Azure-Client>.$Process.AwaitResultAsync@133-2.Invoke(Unit _arg4) in C:\workspace\krontogiannis\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 133
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@787-1.Invoke(a a)
   at MBrace.Core.Internals.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Utils\ExceptionDispatchInfo.fs:line 139
   at MBrace.Azure.Client.Process`1.AwaitResult() in C:\workspace\krontogiannis\MBrace.Azure\src\MBrace.Azure.Client\Process.fs:line 126
   at <StartupCode$FSI_0005>.$FSI_0005.main@()
```

```
 Process                                                                                                                                                                                   

 Name                        Process Id   Status  Completed  Execution Time            Jobs           Result Type           Start Time                  Completion Time            
 ----                        ----------   ------  ---------  --------------            ----           -----------           ----------                  ---------------            
       bb682f54fd3648b9981ac0fe75926fe9  Faulted  True       00:00:02.1708627    0 /   0 /   1 /   1  System.Net.WebClient  27/04/2015 12:30:42 +00:00  27/04/2015 12:30:44 +00:00 
```

**Comment by palladin** [comment]
Thanks!
