### ISSUE TITLE
Issues with SqlType Providers

### ISSUE THREAD

**Issue by cmmurray** [mbraceproject/MBrace.Azure#84]
I could easily be setup wrong but every time I use either a SqlDataConnection or SqlEntityConnection in the same script it results in a VagabondException "ran into duplicate assumblies of qualified name 'tmpXYZ'". Is this a known limitation?

**Comment by eiriktsarpalis** [comment]
It is, but this could be a bug. Could you please provide the precise error message/stracktrace you are getting as well a few basic reproduction steps?

**Comment by cmmurray** [comment]
Sure. The full stack trace is 

Nessos.Vagabond.VagabondException: ran into duplicate assemblies of qualified name 'tmp420C, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. This is not supported.
   at Nessos.Vagabond.Utils.tryGetLoadedAssembly@146.Invoke(String fullName) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 154
   at Nessos.Vagabond.Utils.tryConcurrentMemoize@131.Invoke(a x) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 135
   at Nessos.Vagabond.Utils.tryLoadAssembly(String fullName) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 160
   at Nessos.Vagabond.DependencyAnalysis.tryResolveAssembly(FSharpFunc`2 ignoreF, Boolean requireLoaded, FSharpOption`1 state, String fullName) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 79
   at Nessos.Vagabond.DependencyAnalysis.dependencies@133-1.Invoke(String fullName) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 133
   at Microsoft.FSharp.Collections.ListModule.chooseAllAcc[a,b](FSharpFunc`2 f, FSharpList`1 xs, FSharpList`1 acc)
   at Nessos.Vagabond.DependencyAnalysis.traverse@125(FSharpFunc`2 ignoreF, Boolean requireLoaded, DynamicAssemblyCompilerState state, FSharpMap`2 graph, FSharpList`1 remaining) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 133
   at Nessos.Vagabond.DependencyAnalysis.traverse@125-1.Invoke(FSharpMap`2 graph, FSharpList`1 remaining) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 125
   at Nessos.Vagabond.DependencyAnalysis.parseDynamicAssemblies(FSharpFunc`2 ignoreF, Boolean requireLoaded, DynamicAssemblyCompilerState state, IEnumerable`1 assemblies) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\DependencyAnalysis.fs:line 125
   at Nessos.Vagabond.SliceCompiler.compileDynamicAssemblySlices(FSharpFunc`2 ignoreF, Boolean requireLoaded, DynamicAssemblyCompilerState state, FSharpList`1 assemblies) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\SliceCompiler\SliceCompiler.fs:line 104
   at Nessos.Vagabond.Utils.MailboxProcessor-1-PostAndAsyncReply@198-2.Invoke(Exn`1 _arg1) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 198
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@797-1.Invoke(a a)
   at Nessos.Vagabond.Utils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 112
   at Nessos.Vagabond.Utils.MailboxProcessor`1.PostAndReply[Msg,R](FSharpMailboxProcessor`1 m, FSharpFunc`2 msgB) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Utils.fs:line 202
   at Nessos.Vagabond.VagabondManager.compile(FSharpList`1 assemblies) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Vagabond.fs:line 54
   at Nessos.Vagabond.VagabondManager.ComputeObjectDependencies(Object obj, FSharpOption`1 permitCompilation) in c:\Users\eirik\Development\nessos\Vagabond\src\Vagabond\Vagabond.fs:line 128
   at MBrace.Azure.Runtime.Primitives.BlobAssemblyManager.ComputeDependencies[T](T graph) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Runtime\Primitives\BlobAssemblyManager.fs:line 191
   at <StartupCode$MBrace-Azure-Client>.$Client.CreateProcessAsync@196.Invoke(Unit unitVar) in c:\Users\eirik\Development\mbrace\MBrace.Azure\src\MBrace.Azure.Client\Client.fs:line 198
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@813.Invoke(AsyncParams`1 args)
   at MBrace.Continuation.ExceptionDispatchInfoUtils.Async.RunSync[T](FSharpAsync`1 workflow, FSharpOption`1 cancellationToken) in c:\Users\eirik\Development\mbrace\MBrace.Core\src\MBrace.Core\Continuation\ExceptionDispatchInfo.fs:line 138
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in C:\Users\pwei\Projects\MBraceBugTest\MBraceBugTest\Script1.fsx:line 31
Stopped due to error

You can replicate with any sql db and the following script

#r @"..\packages\FSharp.Data\lib\net40\FSharp.Data.dll"
#r @"FSharp.Data.TypeProviders.dll"
#r @"System.Data.Linq.dll"
#load "credentials.fsx"

open System
open FSharp.Data
open Microsoft.FSharp.Data.TypeProviders
open MBrace
open MBrace.Azure
open MBrace.Azure.Client
open MBrace.Flow
open System.Data.Linq


type dbSchema = SqlDataConnection<"Data Source=localhost;Initial Catalog=tempTest;Integrated Security=SSPI;">
let db = dbSchema.GetDataContext() //comment this line to avoid error

let cluster = Runtime.GetHandle(config)


let quickText = 
    cloud { return "Hello world!" } 
    |> cluster.Run

**Comment by 4ndr1u5** [comment]
maybe you can suggest any workaround for this issue?

**Comment by isaacabraham** [comment]
Out of curiosity, have you retested with latest MBrace? There have been a lot of changes in the last eight months.

**Comment by palladin** [comment]
I have tested and I can confirm that we get exactly the same behaviour.

**Comment by palladin** [comment]
Runnig the following code
```
let asms =  
    AppDomain.CurrentDomain.GetAssemblies() 
    |> Array.filter (fun asm -> asm.GetName().Name.StartsWith("tmp")) 
```
we get
```

val asms : Reflection.Assembly [] =
  [|tmp1B72, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null;
    tmp1C6D, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null;
    tmp1C6D, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|]
```
It generates two assemblies with the same name... so it seems like a bug of the Sql Type Provider.

**Comment by palladin** [comment]
I forgot to mention that the two assemblies contain exactly the same types. I don't know if it is bug of the SqlTypeProvider or by design.

**Comment by eiriktsarpalis** [comment]
I just came across [this issue](https://github.com/fsharp/FSharp.Data/issues/778). It seems like the SqlProvider you are using is not part of the FSharp.Data package, but rather it is found in the legacy `FSharp.Data.TypeProviders.dll` which is bundled with F# 3.0. I would recommend switching to a more recent, erasing type provider such as http://fsprojects.github.io/SQLProvider/

**Comment by palladin** [comment]
And I can confirm that with http://fsprojects.github.io/SQLProvider/ the reproduction example now works.

**Comment by 4ndr1u5** [comment]
Thank you guys :)
